import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./navbar/navbar";
import { Nunito } from 'next/font/google'


export const metadata: Metadata = {
  title: "OnlyMemes",
  description: "Generated by create next app",
};

const roboto_mono = Nunito({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_mono.className}>
        <div className="container">
          <div className="nav-container">
            <Navbar/> {/* This will naturally be at the top */}
          </div>
          <div className="triple-block">
            <div className="block">
              <p className="block-title">OnlyMemes</p>
              <p className="block-subtitle">...and memes only. <br />
              Sign in to share your memes collections!</p>
              <img src="Yao.png" className="cube-icon" />
              <button className="dark-button">
                  15  <img src="user.png" className="user-icon" />
              </button>
            </div>
            <div className="block">Part 2</div>
            <div className="block">Part 3</div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}

